volumes:
  kvdata:

services:
  demo-tv-streaming-db:
    image: ghcr.io/oracle/nosql:latest-ce
    container_name: kvlite
    hostname: kvlite
    environment:
      KV_PROXY_PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - kvdata:/kvroot:rw
  demo-tv-streaming-app:
    image: ghcr.io/dario-vega/demo-tv-streaming-app:latest
    environment:
      NOSQL_ENDPOINT: kvlite
      NOSQL_PORT: 8080
    ports:
      - 3000:3000
